drop table dbelyavsky.qlog_PROD;

create external table dbelyavsky.qlog_PROD (
    version                string,
    dateReceived                string,
    timeReceived                string,
    timeRange                string,
    ipAddress                string,
    serverName                string,
    servletName                string,
    userAgent                string,
    operatingystem                 string,
    host                string,
    sitelet                string,
    vurl                string,
    siteId                string,
    scores                map<string, string>,
    lookupId                string,
    limits                string,
    action                string,
    extAdnetworkId                string,
    extAdvertiserId                string,
    extCampaignId                string,
    extPlanId                string,
    extPublisherId                string,
    extChannelId                string,
    extPlacementId                string,
    extPassbackUrl                string,
    parseMethod                string,
    countryCode                string,
    count                string,
    reason                string,
    stateCode                string,
    passbackId                string,
    reasonElement                string,
    dma                string,
    memHits                string,
    eventType                string,
    userAgentStr                string,
    refUrlType                string,
    javascriptInfo                map<string, string>,
    platform                string,
    isSafe                string,
    ipUserAgentHash                string,
    eventCount                string,
    adtalkTimestamp                string,
    adtalkCall                string,
    flashTimestamp                string,
    flashCall                string,
    unloadTimestamp                string,
    unloadCall                string,
    pings                string,
    dtCount                string,
    impressionScores                map<string, string>,
    impressionScoreWeights                string,
    auxInfo                string,
    ext_bidUrl                string,
    ext_bidPrice                string,
    ext_uid                string,
    ext_impId                string,
    sadEvidence                string,
    exchangeInfo                string,
    macros                string,
    cookieValue                string,
    diagnosticsField                string,
    videoTimestamp                string,
    videoCall                string,
    originalReferringUrl                string,
    mbTimestamp                string,
    mbCall                string,
    scaChallenges                string,
    hundredPercentPings                string,
    videoQuartileHundredPercentPings                string,
    originalIPAddress                string,
    asIdMap                string,
    pubOrder                string,
    pubCreative                string,
    custom                string,
    custom2                string,
    custom3                string,
    oneTimePings                string,
    bundleId                string,
    sdkAppId                string,
    givt                string,
    viewabilityMethod                string,
    scaResults                string,
    discFree                string,
    discFreePassbackId                string,
    discFreeAction                string,
    dtMinimizer                string,
    discFreeReason                string,
    appStoreTypeCode                string,
    selectedBundleId                string,
    selectedBundleIdSource                string,
    identifiedBundleIds                string,
    cmCLogTimestamp                string,
    cmCLog                string,
    cmSubIds                string,
    fraudScores                map<string,string>,
    cmIds                string,
    mrcOutOfViewReason                string,
    auth                string,
    gdprSanitizedIpAddress                string,
    dealId                string
)

ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
COLLECTION ITEMS TERMINATED BY ', '
MAP KEYS TERMINATED BY '='
LINES TERMINATED BY '\n'
LOCATION '/user/dbelyavsky/SAD-4903/test_output/PROD/quality/logs/2018/08/15/12/impressions/';

----------------

drop table dbelyavsky.qlog_BRANCH;

create external table dbelyavsky.qlog_BRANCH (
    version                string,
    dateReceived                string,
    timeReceived                string,
    timeRange                string,
    ipAddress                string,
    serverName                string,
    servletName                string,
    userAgent                string,
    operatingystem                 string,
    host                string,
    sitelet                string,
    vurl                string,
    siteId                string,
    scores                map<string, string>,
    lookupId                string,
    limits                string,
    action                string,
    extAdnetworkId                string,
    extAdvertiserId                string,
    extCampaignId                string,
    extPlanId                string,
    extPublisherId                string,
    extChannelId                string,
    extPlacementId                string,
    extPassbackUrl                string,
    parseMethod                string,
    countryCode                string,
    count                string,
    reason                string,
    stateCode                string,
    passbackId                string,
    reasonElement                string,
    dma                string,
    memHits                string,
    eventType                string,
    userAgentStr                string,
    refUrlType                string,
    javascriptInfo                map<string, string>,
    platform                string,
    isSafe                string,
    ipUserAgentHash                string,
    eventCount                string,
    adtalkTimestamp                string,
    adtalkCall                string,
    flashTimestamp                string,
    flashCall                string,
    unloadTimestamp                string,
    unloadCall                string,
    pings                string,
    dtCount                string,
    impressionScores                map<string, string>,
    impressionScoreWeights                string,
    auxInfo                string,
    ext_bidUrl                string,
    ext_bidPrice                string,
    ext_uid                string,
    ext_impId                string,
    sadEvidence                string,
    exchangeInfo                string,
    macros                string,
    cookieValue                string,
    diagnosticsField                string,
    videoTimestamp                string,
    videoCall                string,
    originalReferringUrl                string,
    mbTimestamp                string,
    mbCall                string,
    scaChallenges                string,
    hundredPercentPings                string,
    videoQuartileHundredPercentPings                string,
    originalIPAddress                string,
    asIdMap                string,
    pubOrder                string,
    pubCreative                string,
    custom                string,
    custom2                string,
    custom3                string,
    oneTimePings                string,
    bundleId                string,
    sdkAppId                string,
    givt                string,
    viewabilityMethod                string,
    scaResults                string,
    discFree                string,
    discFreePassbackId                string,
    discFreeAction                string,
    dtMinimizer                string,
    discFreeReason                string,
    appStoreTypeCode                string,
    selectedBundleId                string,
    selectedBundleIdSource                string,
    identifiedBundleIds                string,
    cmCLogTimestamp                string,
    cmCLog                string,
    cmSubIds                string,
    fraudScores                map<string,string>,
    cmIds                string,
    mrcOutOfViewReason                string,
    auth                string,
    gdprSanitizedIpAddress                string,
    dealId                string
)

ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
COLLECTION ITEMS TERMINATED BY ', '
MAP KEYS TERMINATED BY '='
LINES TERMINATED BY '\n'
LOCATION '/user/dbelyavsky/SAD-4903/test_output/BRANCH/quality/logs/2018/08/15/12/impressions/';
