SELECT UEM.campaignId, UEM.campaignName,
    FORMAT(100*UEM.inViewPct*UEM.scaleFactor, 2) - FORMAT(100*UEM_BRANCH.inViewPct*UEM_BRANCH.scaleFactor, 2) as inViewPct,
    UEM.inViewDisplayImps - UEM_BRANCH.inViewDisplayImps as inViewDisplayImps,
    UEM.inViewVideoImps - UEM_BRANCH.inViewVideoImps as inViewVideoImps,
    (UEM.inViewImps+UEM.outOfViewImps+UEM.suspiciousImps) - (UEM_BRANCH.inViewImps+UEM_BRANCH.outOfViewImps+UEM_BRANCH.suspiciousImps) as measuredImps,
    (UEM.totalUnblockedImps-UEM.inViewImps-UEM.outOfViewImps-UEM.suspiciousImps) - (UEM_BRANCH.totalUnblockedImps-UEM_BRANCH.inViewImps-UEM_BRANCH.outOfViewImps-UEM_BRANCH.suspiciousImps) as unmeasuredImps,
    ((UEM.inViewImps+UEM.outOfViewImps+UEM.suspiciousImps)/UEM.totalUnblockedImps) - ((UEM_BRANCH.inViewImps+UEM_BRANCH.outOfViewImps+UEM_BRANCH.suspiciousImps)/UEM_BRANCH.totalUnblockedImps) as measuredRate,
    ROUND(UEM.suspiciousImps) - ROUND(UEM_BRANCH.suspiciousImps) as suspiciousImps,
    UEM.suspiciousBlockedImps - UEM_BRANCH.suspiciousBlockedImps as suspiciousBlockedImps,
    UEM.totalUnblockedImps - UEM_BRANCH.totalUnblockedImps as totalUnblockedImps,
    UEM.totalBlockedImps - UEM_BRANCH.totalBlockedImps as totalBlockedImps,
    UEM.totalImpressions - UEM_BRANCH.totalImpressions,
    UEM.grossBillableDisplayImps - UEM_BRANCH.grossBillableDisplayImps,
    (ROUND(
    IF(UEM.regularVIDEOInViewImps+UEM.regularVIDEOOutOfViewImps > 0,
        (UEM.regularInViewGt2qUnblockedImps100)/(UEM.regularVIDEOInViewImps+UEM.regularVIDEOOutOfViewImps)*(UEM.regularVIDEOUnblockedImps-UEM.regularVIDEOSuspiciousImps),
        0)
    +
    IF(UEM.parentVIDEOInViewImps+UEM.parentVIDEOOutOfViewImps > 0,
       (UEM.parentInViewGt2qUnblockedImps100)/(UEM.parentVIDEOInViewImps+UEM.parentVIDEOOutOfViewImps)*(UEM.parentVIDEOUnblockedImps + UEM.childVIDEOUnblockedImps - UEM.parentVIDEOSuspiciousImps - UEM.childVIDEOSuspiciousImps),
       0)
      )) -
      (ROUND(
    IF(UEM_BRANCH.regularVIDEOInViewImps+UEM_BRANCH.regularVIDEOOutOfViewImps > 0,
        (UEM_BRANCH.regularInViewGt2qUnblockedImps100)/(UEM_BRANCH.regularVIDEOInViewImps+UEM_BRANCH.regularVIDEOOutOfViewImps)*(UEM_BRANCH.regularVIDEOUnblockedImps-UEM_BRANCH.regularVIDEOSuspiciousImps),
        0)
    +
    IF(UEM_BRANCH.parentVIDEOInViewImps+UEM_BRANCH.parentVIDEOOutOfViewImps > 0,
       (UEM_BRANCH.parentInViewGt2qUnblockedImps100)/(UEM_BRANCH.parentVIDEOInViewImps+UEM_BRANCH.parentVIDEOOutOfViewImps)*(UEM_BRANCH.parentVIDEOUnblockedImps + UEM_BRANCH.childVIDEOUnblockedImps - UEM_BRANCH.parentVIDEOSuspiciousImps - UEM_BRANCH.childVIDEOSuspiciousImps),
       0)
      )) as billableVideoImps,
    UEM.inViewGt2qUnblockedImps100 - UEM_BRANCH.inViewGt2qUnblockedImps100,
    UEM.generalInvalidImps - UEM_BRANCH.generalInvalidImps
FROM
    (SELECT CAMPAIGN_ID as campaignId, CAMPAIGN_NAME as campaignName,
        ROUND(SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (1, 4, 5, 6, 111, 121, 131, 221, 231), IF(Q_DATA_IMPS > IMPS, ((IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS), 0))) as inViewDisplayImps,
        ROUND(SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232), IF(Q_DATA_IMPS > IMPS, ((IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS), 0))) as inViewVideoImps,
        ROUND(SUM(IF(Q_DATA_IMPS > IMPS, ((IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS))) as inViewImps,
        ROUND(SUM(IF(Q_DATA_IMPS > IMPS, ((NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS))) as outOfViewImps,
        FORMAT(SUM(IN_VIEW_PCT*(IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS+NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS+SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS))/SUM(IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS+NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS+SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS), 2) as inViewPct,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) != 3, FULLY_IN_VIEW_THRU_2D_IMPS, 0)) as inViewGt2qUnblockedImps100,
        SUM(SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS) as suspiciousImps,
        SUM(SUSPICIOUS_IMPS-SUSPICIOUS_PASSED_IMPS-SUSPICIOUS_FLAGGED_IMPS) as suspiciousBlockedImps,
        SUM(PASSED_IMPS+FLAGGED_IMPS) totalUnblockedImps,
        SUM(IMPS-PASSED_IMPS-FLAGGED_IMPS) as totalBlockedImps,
        SUM(GENERAL_INVALID_IMPS) as generalInvalidImps,
        SUM(GROSS_BILLABLE_DISPLAY_IMPS) as grossBillableDisplayImps,
        SUM(IMPS) as totalImpressions,
        (
            (1 - (SUM(SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS)/SUM(PASSED_IMPS+FLAGGED_IMPS))) /
                FORMAT(SUM((IN_VIEW_PCT+NOT_IN_VIEW_PCT)*(IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS+NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS+SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS)) / SUM(IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS+NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS+SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS), 2)
        ) as scaleFactor,
        SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 1, PASSED_IMPS+FLAGGED_IMPS, 0)) as regularUnblockedImps,
        SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 2, PASSED_IMPS+FLAGGED_IMPS, 0)) as parentUnblockedImps,
        SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 3, PASSED_IMPS+FLAGGED_IMPS, 0)) as childUnblockedImps,
        SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 1, SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS, 0)) as regularSuspiciousImps,
        SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 2, SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS, 0)) as parentSuspiciousImps,
        SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 3, SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS, 0)) as childSuspiciousImps,
        ROUND(SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 1, IF(Q_DATA_IMPS > IMPS, ((IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS), 0))) as regularInViewImps,
        ROUND(SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 1, IF(Q_DATA_IMPS > IMPS, ((NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS), 0))) as regularOutOfViewImps,
        ROUND(SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 2, IF(Q_DATA_IMPS > IMPS, ((IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS), 0))) as parentInViewImps,
        ROUND(SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 2, IF(Q_DATA_IMPS > IMPS, ((NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS), 0))) as parentOutOfViewImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 1, FULLY_IN_VIEW_THRU_2D_IMPS, 0)) as regularInViewGt2qUnblockedImps100,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (1, 4, 5, 6, 111, 121, 131, 221, 231) AND BILLABLE_DISPLAY_IMPS IS NOT NULL AND COALESCE(ROADBLOCK_STATUS, 1) = 1, BILLABLE_DISPLAY_IMPS, 0)) as regularRawBillableDisplayImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (1, 4, 5, 6, 111, 121, 131, 221, 231) AND BILLABLE_DISPLAY_IMPS IS NULL AND COALESCE(ROADBLOCK_STATUS, 1) = 1, FULLY_IN_VIEW_0S_PASSED_IMPS+FULLY_IN_VIEW_0S_FLAGGED_IMPS, 0)) as regularEstimatedDisplayBillableImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 2, FULLY_IN_VIEW_THRU_2D_IMPS, 0)) as parentInViewGt2qUnblockedImps100,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (1, 4, 5, 6, 111, 121, 131, 221, 231) AND BILLABLE_DISPLAY_IMPS IS NOT NULL AND COALESCE(ROADBLOCK_STATUS, 1) = 2, BILLABLE_DISPLAY_IMPS, 0)) as parentRawBillableDisplayImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (1, 4, 5, 6, 111, 121, 131, 221, 231) AND BILLABLE_DISPLAY_IMPS IS NULL AND COALESCE(ROADBLOCK_STATUS, 1) = 2, FULLY_IN_VIEW_0S_PASSED_IMPS+FULLY_IN_VIEW_0S_FLAGGED_IMPS, 0)) as parentEstimatedDisplayBillableImps,
        ROUND(SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 1, IF(Q_DATA_IMPS > IMPS, ((IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS), 0))) as regularVIDEOInViewImps,
        ROUND(SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 1, IF(Q_DATA_IMPS > IMPS, ((NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS), 0))) as regularVIDEOOutOfViewImps,
        ROUND(SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 2, IF(Q_DATA_IMPS > IMPS, ((IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS), 0))) as parentVIDEOInViewImps,
        ROUND(SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 2, IF(Q_DATA_IMPS > IMPS, ((NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS), 0))) as parentVIDEOOutOfViewImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 1, PASSED_IMPS+FLAGGED_IMPS, 0)) as regularVIDEOUnblockedImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 2, PASSED_IMPS+FLAGGED_IMPS, 0)) as parentVIDEOUnblockedImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 3, PASSED_IMPS+FLAGGED_IMPS, 0)) as childVIDEOUnblockedImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 1, SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS, 0)) as regularVIDEOSuspiciousImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 2, SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS, 0)) as parentVIDEOSuspiciousImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 3, SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS, 0)) as childVIDEOSuspiciousImps

    FROM
        analytics.AGG_AGENCY_QUALITY_V3 WHERE HIT_DATE = "2016-11-20"
    GROUP BY CAMPAIGN_ID
    HAVING SUM(IMPS) >= 0
    ) UEM left join
    (SELECT CAMPAIGN_ID as campaignId, CAMPAIGN_NAME as campaignName,
        ROUND(SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (1, 4, 5, 6, 111, 121, 131, 221, 231), IF(Q_DATA_IMPS > IMPS, ((IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS), 0))) as inViewDisplayImps,
        ROUND(SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232), IF(Q_DATA_IMPS > IMPS, ((IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS), 0))) as inViewVideoImps,
        ROUND(SUM(IF(Q_DATA_IMPS > IMPS, ((IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS))) as inViewImps,
        ROUND(SUM(IF(Q_DATA_IMPS > IMPS, ((NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS))) as outOfViewImps,
        FORMAT(SUM(IN_VIEW_PCT*(IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS+NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS+SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS))/SUM(IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS+NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS+SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS), 2) as inViewPct,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) != 3, FULLY_IN_VIEW_THRU_2D_IMPS, 0)) as inViewGt2qUnblockedImps100,
        SUM(SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS) as suspiciousImps,
        SUM(SUSPICIOUS_IMPS-SUSPICIOUS_PASSED_IMPS-SUSPICIOUS_FLAGGED_IMPS) as suspiciousBlockedImps,
        SUM(PASSED_IMPS+FLAGGED_IMPS) totalUnblockedImps,
        SUM(IMPS-PASSED_IMPS-FLAGGED_IMPS) as totalBlockedImps,
        SUM(GENERAL_INVALID_IMPS) as generalInvalidImps,
        SUM(GROSS_BILLABLE_DISPLAY_IMPS) as grossBillableDisplayImps,
        SUM(IMPS) as totalImpressions,
        (
            (1 - (SUM(SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS)/SUM(PASSED_IMPS+FLAGGED_IMPS))) /
                FORMAT(SUM((IN_VIEW_PCT+NOT_IN_VIEW_PCT)*(IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS+NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS+SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS)) / SUM(IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS+NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS+SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS), 2)
        ) as scaleFactor,
        SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 1, PASSED_IMPS+FLAGGED_IMPS, 0)) as regularUnblockedImps,
        SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 2, PASSED_IMPS+FLAGGED_IMPS, 0)) as parentUnblockedImps,
        SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 3, PASSED_IMPS+FLAGGED_IMPS, 0)) as childUnblockedImps,
        SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 1, SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS, 0)) as regularSuspiciousImps,
        SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 2, SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS, 0)) as parentSuspiciousImps,
        SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 3, SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS, 0)) as childSuspiciousImps,
        ROUND(SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 1, IF(Q_DATA_IMPS > IMPS, ((IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS), 0))) as regularInViewImps,
        ROUND(SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 1, IF(Q_DATA_IMPS > IMPS, ((NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS), 0))) as regularOutOfViewImps,
        ROUND(SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 2, IF(Q_DATA_IMPS > IMPS, ((IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS), 0))) as parentInViewImps,
        ROUND(SUM(IF(COALESCE(ROADBLOCK_STATUS, 1) = 2, IF(Q_DATA_IMPS > IMPS, ((NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS), 0))) as parentOutOfViewImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 1, FULLY_IN_VIEW_THRU_2D_IMPS, 0)) as regularInViewGt2qUnblockedImps100,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (1, 4, 5, 6, 111, 121, 131, 221, 231) AND BILLABLE_DISPLAY_IMPS IS NOT NULL AND COALESCE(ROADBLOCK_STATUS, 1) = 1, BILLABLE_DISPLAY_IMPS, 0)) as regularRawBillableDisplayImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (1, 4, 5, 6, 111, 121, 131, 221, 231) AND BILLABLE_DISPLAY_IMPS IS NULL AND COALESCE(ROADBLOCK_STATUS, 1) = 1, FULLY_IN_VIEW_0S_PASSED_IMPS+FULLY_IN_VIEW_0S_FLAGGED_IMPS, 0)) as regularEstimatedDisplayBillableImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 2, FULLY_IN_VIEW_THRU_2D_IMPS, 0)) as parentInViewGt2qUnblockedImps100,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (1, 4, 5, 6, 111, 121, 131, 221, 231) AND BILLABLE_DISPLAY_IMPS IS NOT NULL AND COALESCE(ROADBLOCK_STATUS, 1) = 2, BILLABLE_DISPLAY_IMPS, 0)) as parentRawBillableDisplayImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (1, 4, 5, 6, 111, 121, 131, 221, 231) AND BILLABLE_DISPLAY_IMPS IS NULL AND COALESCE(ROADBLOCK_STATUS, 1) = 2, FULLY_IN_VIEW_0S_PASSED_IMPS+FULLY_IN_VIEW_0S_FLAGGED_IMPS, 0)) as parentEstimatedDisplayBillableImps,
        ROUND(SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 1, IF(Q_DATA_IMPS > IMPS, ((IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS), 0))) as regularVIDEOInViewImps,
        ROUND(SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 1, IF(Q_DATA_IMPS > IMPS, ((NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS), 0))) as regularVIDEOOutOfViewImps,
        ROUND(SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 2, IF(Q_DATA_IMPS > IMPS, ((IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), IN_VIEW_PASSED_IMPS+IN_VIEW_FLAGGED_IMPS), 0))) as parentVIDEOInViewImps,
        ROUND(SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 2, IF(Q_DATA_IMPS > IMPS, ((NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS)/(Q_DATA_IMPS/IMPS)), NOT_IN_VIEW_PASSED_IMPS+NOT_IN_VIEW_FLAGGED_IMPS), 0))) as parentVIDEOOutOfViewImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 1, PASSED_IMPS+FLAGGED_IMPS, 0)) as regularVIDEOUnblockedImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 2, PASSED_IMPS+FLAGGED_IMPS, 0)) as parentVIDEOUnblockedImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 3, PASSED_IMPS+FLAGGED_IMPS, 0)) as childVIDEOUnblockedImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 1, SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS, 0)) as regularVIDEOSuspiciousImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 2, SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS, 0)) as parentVIDEOSuspiciousImps,
        SUM(IF(COALESCE(MEDIA_TYPE_ID, 1) IN (2, 3, 112, 122, 132, 222, 232) AND COALESCE(ROADBLOCK_STATUS, 1) = 3, SUSPICIOUS_PASSED_IMPS+SUSPICIOUS_FLAGGED_IMPS, 0)) as childVIDEOSuspiciousImps

    FROM
        AGG_AGENCY_QUALITY_V3 WHERE HIT_DATE = "2016-11-20"
    GROUP BY CAMPAIGN_ID
    HAVING SUM(IMPS) >= 0
    ) UEM_BRANCH
    on (UEM.campaignId = UEM_BRANCH.campaignId and UEM.campaignName = UEM_BRANCH.campaignName)
ORDER BY totalUnblockedImps desc;
