SELECT
CAST(
	SUM( IF (MCM_1_SRC = 2
		, IF(MEASUREMENT_SOURCE_TYPE = 'PMI'
			, MCM_1_NON_SUSPICIOUS_IMPS
			, ROUND(
				MCM_1_NON_SUSPICIOUS_IMPS * (
					IF(Q_DATA_IMPS > IMPS
						, ( COALESCE(IN_VIEW_PASSED_IMPS,0) + COALESCE(IN_VIEW_FLAGGED_IMPS,0) + COALESCE(NOT_IN_VIEW_PASSED_IMPS,0) + COALESCE(NOT_IN_VIEW_FLAGGED_IMPS,0) ) * IMPS / Q_DATA_IMPS
						, ( COALESCE(IN_VIEW_PASSED_IMPS,0) + COALESCE(IN_VIEW_FLAGGED_IMPS,0) + COALESCE(NOT_IN_VIEW_PASSED_IMPS,0) + COALESCE(NOT_IN_VIEW_FLAGGED_IMPS,0) )
					)
				) / IMPS
			)
		)
		, 0
	) ) AS SIGNED )
	AS customMetricsId2_totalNetInViewImps
  	, PUBLISHER_ID as publisherId
FROM
	(
	SELECT
		'IAS' AS MEASUREMENT_SOURCE_TYPE,
		MEDIA_TYPE_ID,
		IMPS,
		Q_DATA_IMPS,
		IN_VIEW_PASSED_IMPS,
		IN_VIEW_FLAGGED_IMPS,
		NOT_IN_VIEW_PASSED_IMPS,
		NOT_IN_VIEW_FLAGGED_IMPS,
		AGG_AGENCY_QUALITY_V3.MCM_1_SRC,
		AGG_AGENCY_QUALITY_V3.MCM_1_NON_SUSPICIOUS_IMPS
		, PUBLISHER_ID
	FROM
		AGG_AGENCY_QUALITY_V3
	WHERE
		 (HIT_DATE >= '2018-01-03' AND HIT_DATE <= '2018-01-09')
		AND ( CAMPAIGN_ID IN (SELECT CAMPAIGN_ID FROM ADV_ENTITY WHERE TEAM_ID IN (94)) AND CAMPAIGN_ID > 0  )
	) UNION_WITH_PM_DATA
	GROUP BY PUBLISHER_ID
