SELECT
    totalEligibleForBrandSafetyImps,
    passedImps,
    passedPct,
    failedImps,
    failedPct
    ,
        blockedImps,
        blockedPct,
        failedByLanguageImps,
        failedByLanguagePct,
        failedByContentImps,
        failedByContentPct,
        failedByKeywordImps,
        failedByKeywordPct,
        failedByUrlImps,
        failedByUrlPct,
        failedByGeoImps,
        failedByGeoPct,
        failedByFraudImps,
        failedByFraudPct,
        failedByVisibilityImps,
        failedByVisibilityPct

    , THIS_PERIOD.campaignId,THIS_PERIOD.campaignName,THIS_PERIOD.publisherId,THIS_PERIOD.publisherName,THIS_PERIOD.hitDate
FROM
(
        SELECT
                    SUM(IF(GROSS_IMPS=0, IMPS, GROSS_IMPS)) AS totalEligibleForBrandSafetyImps,
                    SUM(PASSED_IMPS) AS passedImps,
                    ROUND(100 * SUM(PASSED_IMPS) / SUM(IF(GROSS_IMPS=0, IMPS, GROSS_IMPS)), 2)  AS passedPct,
                    SUM(FAILED_IMPS) AS failedImps,
                    ROUND(100 * SUM(FAILED_IMPS) / SUM(IF(GROSS_IMPS=0, IMPS, GROSS_IMPS)), 2)  AS failedPct,
                    SUM(BLOCKED_IMPS) AS blockedImps,
                    ROUND(100 * SUM(BLOCKED_IMPS) / SUM(FAILED_IMPS), 2)  AS blockedPct,
                    SUM(FAILED_ARBITRATION_IMPS) AS failedByContentImps,
                    ROUND(100 * SUM(FAILED_ARBITRATION_IMPS) / SUM(IF(GROSS_IMPS=0, IMPS, GROSS_IMPS)), 2)  AS failedByContentPct,
                    SUM(FAILED_KEYWORD_IMPS) AS failedByKeywordImps,
                    ROUND(100 * SUM(FAILED_KEYWORD_IMPS) / SUM(IF(GROSS_IMPS=0, IMPS, GROSS_IMPS)), 2)  AS failedByKeywordPct,
                    SUM(FAILED_URL_IMPS) AS failedByUrlImps,
                    ROUND(100 * SUM(FAILED_URL_IMPS) / SUM(IF(GROSS_IMPS=0, IMPS, GROSS_IMPS)), 2)  AS failedByUrlPct,
                    SUM(FAILED_GEO_IMPS) AS failedByGeoImps,
                    ROUND(100 * SUM(FAILED_GEO_IMPS) / SUM(IF(GROSS_IMPS=0, IMPS, GROSS_IMPS)), 2)  AS failedByGeoPct,
                    SUM(FAILED_FRAUD_IMPS) AS failedByFraudImps,
                    ROUND(100 * SUM(FAILED_FRAUD_IMPS) / SUM(IF(GROSS_IMPS=0, IMPS, GROSS_IMPS)), 2)  AS failedByFraudPct,
                    SUM(FAILED_VISIBILITY_IMPS) AS failedByVisibilityImps,
                    ROUND(100 * SUM(FAILED_VISIBILITY_IMPS) / SUM(IF(GROSS_IMPS=0, IMPS, GROSS_IMPS)), 2)  AS failedByVisibilityPct,
                    SUM(FAILED_LANG_IMPS) AS failedByLanguageImps,
                    ROUND(100 * SUM(FAILED_LANG_IMPS) / SUM(IF(GROSS_IMPS=0, IMPS, GROSS_IMPS)), 2)  AS failedByLanguagePct
            , CAMPAIGN_ID as campaignId, CAMPAIGN_NAME as campaignName,PUBLISHER_ID as publisherId, PUBLISHER_NAME as publisherName,HIT_DATE as hitDate
        FROM
            (
            SELECT
                GROSS_IMPS,
                IMPS,
                PASSED_IMPS,
                FAILED_IMPS,
                BLOCKED_IMPS,
                FAILED_ARBITRATION_IMPS,
                FAILED_KEYWORD_IMPS,
                FAILED_URL_IMPS,
                FAILED_GEO_IMPS,
                FAILED_FRAUD_IMPS,
                FAILED_VISIBILITY_IMPS,
                FAILED_LANG_IMPS
                , CAMPAIGN_ID, CAMPAIGN_NAME,PUBLISHER_ID, PUBLISHER_NAME,HIT_DATE
            FROM
                AGG_AGENCY_BRANDSAFETY
            WHERE
                 (HIT_DATE >= '2018-01-16' AND HIT_DATE <= '2018-01-22')
                AND ( CAMPAIGN_ID IN (SELECT CAMPAIGN_ID FROM ADV_ENTITY WHERE TEAM_ID IN (94)) AND CAMPAIGN_ID > 0  AND CAMPAIGN_ID IN (123966,121966,122253,119247,119246,127649,122254,121028,123421,123423,119235,122244,119233,119242,122796,122243,122349,128039,122352,127171,122350,122250,122251,104908,123109,61243)  )

            UNION ALL

            SELECT
                NULL AS GROSS_IMPS,
                NULL AS IMPS,
                NULL AS PASSED_IMPS,
                NULL AS FAILED_IMPS,
                NULL AS BLOCKED_IMPS,
                NULL AS FAILED_ARBITRATION_IMPS,
                NULL AS FAILED_KEYWORD_IMPS,
                NULL AS FAILED_URL_IMPS,
                NULL AS FAILED_GEO_IMPS,
                NULL AS FAILED_FRAUD_IMPS,
                NULL AS FAILED_VISIBILITY_IMPS,
                NULL AS FAILED_LANG_IMPS
                , CAMPAIGN_PM.CAMPAIGN_ID as CAMPAIGN_ID, CAMPAIGN.NAME as CAMPAIGN_NAME,PUBLISHER_PM.PUBLISHER_ID as PUBLISHER_ID, PUBLISHER_PM.NAME as PUBLISHER_NAME,HIT_DATE
            FROM
                AGG_PARTNER_MEASURED_VIEWABILITY VIEWABILITY_PM
                    JOIN (SELECT ID, MEASUREMENT_SOURCE_ID, NAME, CAMPAIGN_ID FROM PARTNER_MEASURED_CAMPAIGN where CAMPAIGN_ID > 0 ) CAMPAIGN_PM ON (VIEWABILITY_PM.PARTNER_MEASURED_CAMPAIGN_ID=CAMPAIGN_PM.ID AND
                               VIEWABILITY_PM.MEASUREMENT_SOURCE_ID = CAMPAIGN_PM.MEASUREMENT_SOURCE_ID)
                    JOIN CAMPAIGN ON CAMPAIGN_PM.CAMPAIGN_ID=CAMPAIGN.ID
                    LEFT JOIN (SELECT ms.ID as MEASUREMENT_SOURCE_ID, pub.NAME as NAME, pe.PUBLISHER_ID as PUBLISHER_ID FROM MEASUREMENT_SOURCE ms LEFT JOIN PUB_ENTITY pe
                                ON ms.PUB_ENTITY_ID = pe.ID LEFT JOIN PUBLISHER pub on pe.PUBLISHER_ID = pub.ID) PUBLISHER_PM ON VIEWABILITY_PM.MEASUREMENT_SOURCE_ID = PUBLISHER_PM.MEASUREMENT_SOURCE_ID

            WHERE
                 (HIT_DATE >= '2018-01-16' AND HIT_DATE <= '2018-01-22')
                AND ( CAMPAIGN_PM.CAMPAIGN_ID IN (SELECT CAMPAIGN_ID FROM ADV_ENTITY WHERE TEAM_ID IN (94)) AND CAMPAIGN_ID > 0  AND CAMPAIGN_ID IN (123966,121966,122253,119247,119246,127649,122254,121028,123421,123423,119235,122244,119233,119242,122796,122243,122349,128039,122352,127171,122350,122250,122251,104908,123109,61243)  )

            UNION ALL

            SELECT
                NULL AS GROSS_IMPS,
                NULL AS IMPS,
                NULL AS PASSED_IMPS,
                NULL AS FAILED_IMPS,
                NULL AS BLOCKED_IMPS,
                NULL AS FAILED_ARBITRATION_IMPS,
                NULL AS FAILED_KEYWORD_IMPS,
                NULL AS FAILED_URL_IMPS,
                NULL AS FAILED_GEO_IMPS,
                NULL AS FAILED_FRAUD_IMPS,
                NULL AS FAILED_VISIBILITY_IMPS,
                NULL AS FAILED_LANG_IMPS
                , CAMPAIGN_PM.CAMPAIGN_ID as CAMPAIGN_ID, CAMPAIGN.NAME as CAMPAIGN_NAME,PUBLISHER_PM.PUBLISHER_ID as PUBLISHER_ID, PUBLISHER_PM.NAME as PUBLISHER_NAME,HIT_DATE
            FROM
                AGG_FACEBOOK_VIEWABILITY
                    JOIN PARTNER_MEASURED_CAMPAIGN_MAPPING MAPPING ON (AGG_FACEBOOK_VIEWABILITY.MEASUREMENT_SOURCE_ID = MAPPING.MEASUREMENT_SOURCE_ID AND AGG_FACEBOOK_VIEWABILITY.AD_ID = MAPPING.EXT_MAPPING_ID)
                    JOIN (SELECT ID, MEASUREMENT_SOURCE_ID, NAME, CAMPAIGN_ID, STATUS FROM PARTNER_MEASURED_CAMPAIGN where CAMPAIGN_ID > 0 ) CAMPAIGN_PM ON (MAPPING.EXT_CAMPAIGN_ID=CAMPAIGN_PM.ID AND
                               AGG_FACEBOOK_VIEWABILITY.MEASUREMENT_SOURCE_ID = CAMPAIGN_PM.MEASUREMENT_SOURCE_ID)
                    JOIN CAMPAIGN ON CAMPAIGN_PM.CAMPAIGN_ID=CAMPAIGN.ID
                    LEFT JOIN (SELECT ms.ID as MEASUREMENT_SOURCE_ID, pub.NAME as NAME, pe.PUBLISHER_ID as PUBLISHER_ID FROM MEASUREMENT_SOURCE ms LEFT JOIN PUB_ENTITY pe
                                ON ms.PUB_ENTITY_ID = pe.ID LEFT JOIN PUBLISHER as pub on pe.PUBLISHER_ID = pub.ID) PUBLISHER_PM ON AGG_FACEBOOK_VIEWABILITY.MEASUREMENT_SOURCE_ID = PUBLISHER_PM.MEASUREMENT_SOURCE_ID

            WHERE
                 (HIT_DATE >= '2018-01-16' AND HIT_DATE <= '2018-01-22')
                AND ( CAMPAIGN_PM.CAMPAIGN_ID IN (SELECT CAMPAIGN_ID FROM ADV_ENTITY WHERE TEAM_ID IN (94)) AND CAMPAIGN_ID > 0  AND CAMPAIGN_ID IN (123966,121966,122253,119247,119246,127649,122254,121028,123421,123423,119235,122244,119233,119242,122796,122243,122349,128039,122352,127171,122350,122250,122251,104908,123109,61243)  )
            ) UNION_WITH_PM_DATA
        GROUP BY CAMPAIGN_ID,PUBLISHER_ID,HIT_DATE
     HAVING totalEligibleForBrandSafetyImps >= 0
) THIS_PERIOD

ORDER BY totalEligibleForBrandSafetyImps desc
 LIMIT 100000 OFFSET 0 
