SELECT
    totalNetEligibleImps,
    totalNetMeasuredImps,
    totalNetMeasuredPct,
    totalNetInViewImps,
    totalNetInViewPct,
    totalNetOutOfViewImps,
    totalNetOutOfViewPct
    , THIS_PERIOD.campaignId,THIS_PERIOD.campaignName,THIS_PERIOD.publisherId,THIS_PERIOD.publisherName,THIS_PERIOD.hitDate
FROM
(
        SELECT
                    FLOOR(SUM(COALESCE(PASSED_IMPS, IMPS) + COALESCE(FLAGGED_IMPS, 0) - COALESCE(SUSPICIOUS_PASSED_IMPS, SUSPICIOUS_IMPS) - COALESCE(SUSPICIOUS_FLAGGED_IMPS, 0))) AS totalNetEligibleImps,
                    CAST((FLOOR(SUM(
                        IF (FACEBOOK_GROUPM_DISPLAY_MEASURED_IMPS IS NULL,
                            IF(Q_DATA_IMPS > IMPS, ((COALESCE(IN_VIEW_PASSED_IMPS, 0) + COALESCE(IN_VIEW_FLAGGED_IMPS, 0)) / (Q_DATA_IMPS / IMPS)), COALESCE(IN_VIEW_PASSED_IMPS ,0) + COALESCE(IN_VIEW_FLAGGED_IMPS ,0))
                            ,
                            FACEBOOK_GROUPM_DISPLAY_MEASURED_IMPS
                        )
                    )) + FLOOR(SUM(
                        IF (FACEBOOK_GROUPM_DISPLAY_MEASURED_IMPS IS NULL,
                            IF(Q_DATA_IMPS > IMPS, ((COALESCE(NOT_IN_VIEW_PASSED_IMPS ,0) + COALESCE(NOT_IN_VIEW_FLAGGED_IMPS, 0)) / (Q_DATA_IMPS / IMPS)), COALESCE(NOT_IN_VIEW_PASSED_IMPS, 0) + COALESCE(NOT_IN_VIEW_FLAGGED_IMPS, 0))
                            ,
                            0
                        )
                    ))) AS SIGNED) AS totalNetMeasuredImps,
                    ROUND(100 * CAST((FLOOR(SUM(
                    IF (FACEBOOK_GROUPM_DISPLAY_MEASURED_IMPS IS NULL,
                        IF(Q_DATA_IMPS > IMPS, ((COALESCE(IN_VIEW_PASSED_IMPS, 0) + COALESCE(IN_VIEW_FLAGGED_IMPS, 0)) / (Q_DATA_IMPS / IMPS)), COALESCE(IN_VIEW_PASSED_IMPS ,0) + COALESCE(IN_VIEW_FLAGGED_IMPS ,0))
                        ,
                        FACEBOOK_GROUPM_DISPLAY_MEASURED_IMPS
                    )
                )) + FLOOR(SUM(
                    IF (FACEBOOK_GROUPM_DISPLAY_MEASURED_IMPS IS NULL,
                        IF(Q_DATA_IMPS > IMPS, ((COALESCE(NOT_IN_VIEW_PASSED_IMPS ,0) + COALESCE(NOT_IN_VIEW_FLAGGED_IMPS, 0)) / (Q_DATA_IMPS / IMPS)), COALESCE(NOT_IN_VIEW_PASSED_IMPS, 0) + COALESCE(NOT_IN_VIEW_FLAGGED_IMPS, 0))
                        ,
                        0
                    )
                ))) AS SIGNED) / FLOOR(SUM(COALESCE(PASSED_IMPS, IMPS) + COALESCE(FLAGGED_IMPS, 0) - COALESCE(SUSPICIOUS_PASSED_IMPS, SUSPICIOUS_IMPS) - COALESCE(SUSPICIOUS_FLAGGED_IMPS, 0))), 2) AS totalNetMeasuredPct,
                    FLOOR(SUM(IF(Q_DATA_IMPS > IMPS, ((COALESCE(IN_VIEW_PASSED_IMPS, 0) + COALESCE(IN_VIEW_FLAGGED_IMPS, 0)) / (Q_DATA_IMPS / IMPS)), COALESCE(IN_VIEW_PASSED_IMPS ,0) + COALESCE(IN_VIEW_FLAGGED_IMPS ,0)))) AS totalNetInViewImps,
                    ROUND(100 * FLOOR(SUM(IF(Q_DATA_IMPS > IMPS, ((COALESCE(IN_VIEW_PASSED_IMPS, 0) + COALESCE(IN_VIEW_FLAGGED_IMPS, 0)) / (Q_DATA_IMPS / IMPS)), COALESCE(IN_VIEW_PASSED_IMPS ,0) + COALESCE(IN_VIEW_FLAGGED_IMPS ,0)))) / CAST((FLOOR(SUM(
                    IF (FACEBOOK_GROUPM_DISPLAY_MEASURED_IMPS IS NULL,
                        IF(Q_DATA_IMPS > IMPS, ((COALESCE(IN_VIEW_PASSED_IMPS, 0) + COALESCE(IN_VIEW_FLAGGED_IMPS, 0)) / (Q_DATA_IMPS / IMPS)), COALESCE(IN_VIEW_PASSED_IMPS ,0) + COALESCE(IN_VIEW_FLAGGED_IMPS ,0))
                        ,
                        FACEBOOK_GROUPM_DISPLAY_MEASURED_IMPS
                    )
                )) + FLOOR(SUM(
                    IF (FACEBOOK_GROUPM_DISPLAY_MEASURED_IMPS IS NULL,
                        IF(Q_DATA_IMPS > IMPS, ((COALESCE(NOT_IN_VIEW_PASSED_IMPS ,0) + COALESCE(NOT_IN_VIEW_FLAGGED_IMPS, 0)) / (Q_DATA_IMPS / IMPS)), COALESCE(NOT_IN_VIEW_PASSED_IMPS, 0) + COALESCE(NOT_IN_VIEW_FLAGGED_IMPS, 0))
                        ,
                        0
                    )
                ))) AS SIGNED), 2) AS totalNetInViewPct,
                    FLOOR(SUM(IF(Q_DATA_IMPS > IMPS, ((COALESCE(NOT_IN_VIEW_PASSED_IMPS ,0) + COALESCE(NOT_IN_VIEW_FLAGGED_IMPS, 0)) / (Q_DATA_IMPS / IMPS)), COALESCE(NOT_IN_VIEW_PASSED_IMPS, 0) + COALESCE(NOT_IN_VIEW_FLAGGED_IMPS, 0)))) AS totalNetOutOfViewImps,
                    ROUND(100 * FLOOR(SUM(IF(Q_DATA_IMPS > IMPS, ((COALESCE(NOT_IN_VIEW_PASSED_IMPS ,0) + COALESCE(NOT_IN_VIEW_FLAGGED_IMPS, 0)) / (Q_DATA_IMPS / IMPS)), COALESCE(NOT_IN_VIEW_PASSED_IMPS, 0) + COALESCE(NOT_IN_VIEW_FLAGGED_IMPS, 0)))) / CAST((FLOOR(SUM(
                    IF (FACEBOOK_GROUPM_DISPLAY_MEASURED_IMPS IS NULL,
                        IF(Q_DATA_IMPS > IMPS, ((COALESCE(IN_VIEW_PASSED_IMPS, 0) + COALESCE(IN_VIEW_FLAGGED_IMPS, 0)) / (Q_DATA_IMPS / IMPS)), COALESCE(IN_VIEW_PASSED_IMPS ,0) + COALESCE(IN_VIEW_FLAGGED_IMPS ,0))
                        ,
                        FACEBOOK_GROUPM_DISPLAY_MEASURED_IMPS
                    )
                )) + FLOOR(SUM(
                    IF (FACEBOOK_GROUPM_DISPLAY_MEASURED_IMPS IS NULL,
                        IF(Q_DATA_IMPS > IMPS, ((COALESCE(NOT_IN_VIEW_PASSED_IMPS ,0) + COALESCE(NOT_IN_VIEW_FLAGGED_IMPS, 0)) / (Q_DATA_IMPS / IMPS)), COALESCE(NOT_IN_VIEW_PASSED_IMPS, 0) + COALESCE(NOT_IN_VIEW_FLAGGED_IMPS, 0))
                        ,
                        0
                    )
                ))) AS SIGNED), 2) AS totalNetOutOfViewPct
            , CAMPAIGN_ID as campaignId, CAMPAIGN_NAME as campaignName,PUBLISHER_ID as publisherId, PUBLISHER_NAME as publisherName,HIT_DATE as hitDate
        FROM
            (
            SELECT
                MEDIA_TYPE_ID,
                IMPS,
                Q_DATA_IMPS,
                SUSPICIOUS_IMPS,
                COALESCE(PASSED_IMPS, 0) AS PASSED_IMPS,
                COALESCE(FLAGGED_IMPS, 0) AS FLAGGED_IMPS,
                COALESCE(SUSPICIOUS_PASSED_IMPS, 0) AS SUSPICIOUS_PASSED_IMPS,
                COALESCE(SUSPICIOUS_FLAGGED_IMPS, 0) AS SUSPICIOUS_FLAGGED_IMPS,
                IN_VIEW_PASSED_IMPS,
                IN_VIEW_FLAGGED_IMPS,
                NOT_IN_VIEW_PASSED_IMPS,
                NOT_IN_VIEW_FLAGGED_IMPS
                , NULL AS FACEBOOK_GROUPM_DISPLAY_MEASURED_IMPS

                , CAMPAIGN_ID, CAMPAIGN_NAME,PUBLISHER_ID, PUBLISHER_NAME,HIT_DATE
            FROM
                AGG_AGENCY_QUALITY_V3
            WHERE
                 (HIT_DATE >= '2018-01-16' AND HIT_DATE <= '2018-01-22')
                AND ( CAMPAIGN_ID IN (SELECT CAMPAIGN_ID FROM ADV_ENTITY WHERE TEAM_ID IN (94)) AND CAMPAIGN_ID > 0  AND CAMPAIGN_ID IN (123966,121966,122253,119247,119246,127649,122254,121028,123421,123423,119235,122244,119233,119242,122796,122243,122349,128039,122352,127171,122350,122250,122251,104908,123109,61243)  )

            UNION ALL

            SELECT
                MEDIA_TYPE_ID,
                IMPS,
                IMPS as Q_DATA_IMPS,
                SUSPICIOUS_IMPS,
                NULL as PASSED_IMPS,
                NULL as FLAGGED_IMPS,
                NULL as SUSPICIOUS_PASSED_IMPS,
                NULL as SUSPICIOUS_FLAGGED_IMPS,
                IN_VIEW_IMPS as IN_VIEW_PASSED_IMPS,
                0 as IN_VIEW_FLAGGED_IMPS,
                NOT_IN_VIEW_IMPS as NOT_IN_VIEW_PASSED_IMPS,
                0 as NOT_IN_VIEW_FLAGGED_IMPS
                , NULL AS FACEBOOK_GROUPM_DISPLAY_MEASURED_IMPS

                , CAMPAIGN_PM.CAMPAIGN_ID as CAMPAIGN_ID, CAMPAIGN.NAME as CAMPAIGN_NAME,PUBLISHER_PM.PUBLISHER_ID as PUBLISHER_ID, PUBLISHER_PM.NAME as PUBLISHER_NAME,HIT_DATE
            FROM
                AGG_PARTNER_MEASURED_VIEWABILITY VIEWABILITY_PM
                    JOIN (SELECT ID, MEASUREMENT_SOURCE_ID, NAME, CAMPAIGN_ID FROM PARTNER_MEASURED_CAMPAIGN where CAMPAIGN_ID > 0 ) CAMPAIGN_PM ON (VIEWABILITY_PM.PARTNER_MEASURED_CAMPAIGN_ID=CAMPAIGN_PM.ID AND
                               VIEWABILITY_PM.MEASUREMENT_SOURCE_ID = CAMPAIGN_PM.MEASUREMENT_SOURCE_ID)
                    JOIN CAMPAIGN ON CAMPAIGN_PM.CAMPAIGN_ID=CAMPAIGN.ID
                    LEFT JOIN (SELECT ms.ID as MEASUREMENT_SOURCE_ID, pub.NAME as NAME, pe.PUBLISHER_ID as PUBLISHER_ID FROM MEASUREMENT_SOURCE ms LEFT JOIN PUB_ENTITY pe
                                ON ms.PUB_ENTITY_ID = pe.ID LEFT JOIN PUBLISHER pub on pe.PUBLISHER_ID = pub.ID) PUBLISHER_PM ON VIEWABILITY_PM.MEASUREMENT_SOURCE_ID = PUBLISHER_PM.MEASUREMENT_SOURCE_ID

            WHERE
                 (HIT_DATE >= '2018-01-16' AND HIT_DATE <= '2018-01-22')
                AND ( CAMPAIGN_PM.CAMPAIGN_ID IN (SELECT CAMPAIGN_ID FROM ADV_ENTITY WHERE TEAM_ID IN (94)) AND CAMPAIGN_ID > 0  AND CAMPAIGN_ID IN (123966,121966,122253,119247,119246,127649,122254,121028,123421,123423,119235,122244,119233,119242,122796,122243,122349,128039,122352,127171,122350,122250,122251,104908,123109,61243)  )

            UNION ALL

            SELECT
                MEDIA_TYPE_ID,
                IF (CAST((MEDIA_TYPE_ID MOD 10) AS SIGNED) = 1,
                    (DETERMINISTIC_IMPS + SUSPICIOUS_IMPS),
                    (IMPS - FACEBOOK_INVALID_IMPS)
                ) as IMPS,
                IF (CAST((MEDIA_TYPE_ID MOD 10) AS SIGNED) = 1,
                    (DETERMINISTIC_IMPS + SUSPICIOUS_IMPS),
                    (IMPS - FACEBOOK_INVALID_IMPS)
                ) as Q_DATA_IMPS,
                SUSPICIOUS_IMPS,
                NULL as PASSED_IMPS,
                NULL as FLAGGED_IMPS,
                NULL as SUSPICIOUS_PASSED_IMPS,
                NULL as SUSPICIOUS_FLAGGED_IMPS,
                IN_VIEW_IMPS as IN_VIEW_PASSED_IMPS,
                0 as IN_VIEW_FLAGGED_IMPS,
                IF (CAST((MEDIA_TYPE_ID MOD 10) AS SIGNED) = 1,
                    (MEASURED_IMPS - IN_VIEW_IMPS),
                    (IMPS - FACEBOOK_INVALID_IMPS - SUSPICIOUS_IMPS - IN_VIEW_IMPS)
                ) as NOT_IN_VIEW_PASSED_IMPS,
                0 as NOT_IN_VIEW_FLAGGED_IMPS
                , NULL AS FACEBOOK_GROUPM_DISPLAY_MEASURED_IMPS

                , CAMPAIGN_PM.CAMPAIGN_ID as CAMPAIGN_ID, CAMPAIGN.NAME as CAMPAIGN_NAME,PUBLISHER_PM.PUBLISHER_ID as PUBLISHER_ID, PUBLISHER_PM.NAME as PUBLISHER_NAME,HIT_DATE
            FROM
                AGG_FACEBOOK_VIEWABILITY
                    JOIN PARTNER_MEASURED_CAMPAIGN_MAPPING MAPPING ON (AGG_FACEBOOK_VIEWABILITY.MEASUREMENT_SOURCE_ID = MAPPING.MEASUREMENT_SOURCE_ID AND AGG_FACEBOOK_VIEWABILITY.AD_ID = MAPPING.EXT_MAPPING_ID)
                    JOIN (SELECT ID, MEASUREMENT_SOURCE_ID, NAME, CAMPAIGN_ID, STATUS FROM PARTNER_MEASURED_CAMPAIGN where CAMPAIGN_ID > 0 ) CAMPAIGN_PM ON (MAPPING.EXT_CAMPAIGN_ID=CAMPAIGN_PM.ID AND
                               AGG_FACEBOOK_VIEWABILITY.MEASUREMENT_SOURCE_ID = CAMPAIGN_PM.MEASUREMENT_SOURCE_ID)
                    JOIN CAMPAIGN ON CAMPAIGN_PM.CAMPAIGN_ID=CAMPAIGN.ID
                    LEFT JOIN (SELECT ms.ID as MEASUREMENT_SOURCE_ID, pub.NAME as NAME, pe.PUBLISHER_ID as PUBLISHER_ID FROM MEASUREMENT_SOURCE ms LEFT JOIN PUB_ENTITY pe
                                ON ms.PUB_ENTITY_ID = pe.ID LEFT JOIN PUBLISHER as pub on pe.PUBLISHER_ID = pub.ID) PUBLISHER_PM ON AGG_FACEBOOK_VIEWABILITY.MEASUREMENT_SOURCE_ID = PUBLISHER_PM.MEASUREMENT_SOURCE_ID

            WHERE
                 (HIT_DATE >= '2018-01-16' AND HIT_DATE <= '2018-01-22')
                AND ( CAMPAIGN_PM.CAMPAIGN_ID IN (SELECT CAMPAIGN_ID FROM ADV_ENTITY WHERE TEAM_ID IN (94)) AND CAMPAIGN_ID > 0  AND CAMPAIGN_ID IN (123966,121966,122253,119247,119246,127649,122254,121028,123421,123423,119235,122244,119233,119242,122796,122243,122349,128039,122352,127171,122350,122250,122251,104908,123109,61243)  )
            ) UNION_WITH_PM_DATA
        GROUP BY CAMPAIGN_ID,PUBLISHER_ID,HIT_DATE
     HAVING totalNetEligibleImps >= 0
) THIS_PERIOD

ORDER BY totalNetEligibleImps desc
 LIMIT 100000 OFFSET 0 
